// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package org.azri.estore.mobile;


public class GetOrderStatus {
    protected java.lang.String string_1;
    
    public GetOrderStatus() {
    }
    
    public GetOrderStatus(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
}
