// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package org.azri.estore.mobile;

public interface OrderStatusSEI extends java.rmi.Remote {
	public java.lang.String getOrderStatus(java.lang.String string_1) throws java.rmi.RemoteException;

}
